name: Build Windows

on: [ push, pull_request ]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Required Build Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib
          sudo apt-get install --no-install-recommends -y libopenjp2-tools

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo apt install software-properties-common
          sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/ bionic main'
          wget -qO- https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/Release.key | sudo apt-key add -
          sudo sh -c 'echo "deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./" > /etc/apt/sources.list.d/obs.list'
          sudo apt update
          sudo apt-get install --install-recommends winehq-stable

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Compile
        run: |
          export NODE_OPTIONS=--max-old-space-size=4096
          npm run ci-compile:win32
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: dist

#      - name: Release
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          draft: true
#          files: "dist/**"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
