name: Build Windows

on: [ push, pull_request ]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Required Build Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib
          sudo apt-get install --no-install-recommends -y libopenjp2-tools

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          wget -nc https://dl.winehq.org/wine-builds/winehq.key
          sudo apt-key add winehq.key
          sudo apt update
          sudo apt install --install-recommends winehq-stable

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Compile
        run: |
          export NODE_OPTIONS=--max-old-space-size=4096
          npm run ci-compile:win32
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: dist

#      - name: Release
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          draft: true
#          files: "dist/**"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
