name: Build

on: [ push ]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Required Build Toolchain (Windows, Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib
          sudo apt-get install --no-install-recommends -y libopenjp2-tools

      - name: Set "NODE_OPTIONS" (Windows, Linux)
        if: matrix.os == 'windows-latest'
        run: |
          set NODE_OPTIONS="--max-old-space-size=6144 --gc_interval=100"
          echo %NODE_OPTIONS%

      - name: Set "NODE_OPTIONS" (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          export NODE_OPTIONS="--max-old-space-size=10240 --gc_interval=100"
          echo $NODE_OPTIONS

      - name: Set "NODE_OPTIONS" Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          export NODE_OPTIONS="--max-old-space-size=6144 --gc_interval=100"
          echo $NODE_OPTIONS

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Compile (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run ci-compile:win32
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Compile (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run ci-compile:darwin
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Compile (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run ci-compile:linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: dist

#      - name: Release
#        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          draft: true
#          files: "dist/**"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
